// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/21/2025, 9:48:08 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/dodo/code/mycoder1/hello-world/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dodo/code/mycoder1/hello-world/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dodo/code/mycoder1/hello-world/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dodo/code/mycoder1/hello-world/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dodo/code/mycoder1/hello-world/plugins/**/*.{js,ts,mjs}","/Users/dodo/code/mycoder1/hello-world/composables/**/*.{js,ts,mjs}","/Users/dodo/code/mycoder1/hello-world/utils/**/*.{js,ts,mjs}","/Users/dodo/code/mycoder1/hello-world/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/dodo/code/mycoder1/hello-world/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/dodo/code/mycoder1/hello-world/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;